### ISSUE TITLE
What is the purpose of this repository?

### ISSUE THREAD

**Issue by cmastalli** [Gepetto/memmo_laas_models#1]
There was created an empty previous repository here: https://gitlab.laas.fr/gepetto/gerard-bauzil.

It makes sense for me to rename this repository to `gerard-bauzil` (including renaming the URDF / meshes files).

Is this OK for you?

---

Additionally, I would like to make few adjustments to easy install /  use as done in `example-robot-data`.
I am happy to do it if somebodies disagree.

**Comment by nim65s** [comment]
https://gitlab.laas.fr/gepetto/gerard-bauzil is not empty. I just noticed that it is private. However, it is public on robotpkg. An issue about that is tracked here: https://gitlab.laas.fr/gepetto/gerard-bauzil/-/issues/1

**Comment by nim65s** [comment]
https://github.com/Gepetto/gerard-bauzil is available

Now, @olivier-stasse : do you think we should take the content of this (memmo_laas_models) repository, and put it in the anterior (gerard-bauzil) one ?

**Comment by cmastalli** [comment]
@nim65s and @olivier-stasse , it seems the contain is already there. To be concretely, I think this is the URDF: https://github.com/Gepetto/gerard-bauzil/blob/master/urdf/staircases_koroibot.urdf

Maybe this repository should disappear, right?

**Comment by nim65s** [comment]
I actually suspected that, and when I tried to find this, I failed. I think it's getting too hot here for my brain to function correctly.

I'm archiving this repository, if anybody have any trouble with this, please open an issue on https://github.com/Gepetto/gerard-bauzil
